//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetFriend.MobileApp.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BetFriend.MobileApp.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Demande d&apos;ami.
        /// </summary>
        public static string AddedMe {
            get {
                return ResourceManager.GetString("AddedMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous n&apos;avez pas encore de compte ?.
        /// </summary>
        public static string AskAccount {
            get {
                return ResourceManager.GetString("AskAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Demande d&apos;ajout envoyée.
        /// </summary>
        public static string AskFriendSent {
            get {
                return ResourceManager.GetString("AskFriendSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Réponse trop tardive pour ce pari.
        /// </summary>
        public static string BadAnswerDate {
            get {
                return ResourceManager.GetString("BadAnswerDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cette date de fin de pari n&apos;est pas possible.
        /// </summary>
        public static string BadBetDate {
            get {
                return ResourceManager.GetString("BadBetDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Informations incorrectes.
        /// </summary>
        public static string BadConnectionInfo {
            get {
                return ResourceManager.GetString("BadConnectionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mauvais format.
        /// </summary>
        public static string BadFormat {
            get {
                return ResourceManager.GetString("BadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Non autorisé.
        /// </summary>
        public static string BadInformations {
            get {
                return ResourceManager.GetString("BadInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pari introuvable.
        /// </summary>
        public static string BetNotFound {
            get {
                return ResourceManager.GetString("BetNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce pari est déjà terminé.
        /// </summary>
        public static string BetOver {
            get {
                return ResourceManager.GetString("BetOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à S&apos;inscrire.
        /// </summary>
        public static string BtnTextRegister {
            get {
                return ResourceManager.GetString("BtnTextRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier mon mot de passe.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choisissez des amis pour ce pari.
        /// </summary>
        public static string ChooseFriends {
            get {
                return ResourceManager.GetString("ChooseFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmer le nouveau mot de passe.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmer le mot de passe.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mot de passe actuel.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date de fin du pari.
        /// </summary>
        public static string DateEndToBet {
            get {
                return ResourceManager.GetString("DateEndToBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date pour parier.
        /// </summary>
        public static string DateToBet {
            get {
                return ResourceManager.GetString("DateToBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Un champ est vide.
        /// </summary>
        public static string EmptyField {
            get {
                return ResourceManager.GetString("EmptyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date de fin : .
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur est survenue.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Informations d&apos;identification inconnues.
        /// </summary>
        public static string ErrorBadConnection {
            get {
                return ResourceManager.GetString("ErrorBadConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La date pour répondre au pari ne peut pas être après la date de fin du pari.
        /// </summary>
        public static string ErrorDateAnswerBet {
            get {
                return ResourceManager.GetString("ErrorDateAnswerBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La date pour répondre au pari ne peut pas être inférieure à la date du jour.
        /// </summary>
        public static string ErrorDateAnswerBetDateNow {
            get {
                return ResourceManager.GetString("ErrorDateAnswerBetDateNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les mots de passe ne sont pas identiques.
        /// </summary>
        public static string ErrorDifferentPassword {
            get {
                return ResourceManager.GetString("ErrorDifferentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La date de fin du pari ne peut pas être inférieure à la date du jour.
        /// </summary>
        public static string ErrorEndDateBet {
            get {
                return ResourceManager.GetString("ErrorEndDateBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cette adresse mail n&apos;est pas valide.
        /// </summary>
        public static string ErrorInvalidEmail {
            get {
                return ResourceManager.GetString("ErrorInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce numéro de téléphone n&apos;est pas valide.
        /// </summary>
        public static string ErrorInvalidPhoneNumber {
            get {
                return ResourceManager.GetString("ErrorInvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le mot de passe doit contenir 6 caractères minimum.
        /// </summary>
        public static string ErrorLengthPassword {
            get {
                return ResourceManager.GetString("ErrorLengthPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tous les paramètres ne sont pas renseignés.
        /// </summary>
        public static string ErrorMissingParameters {
            get {
                return ResourceManager.GetString("ErrorMissingParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Échec.
        /// </summary>
        public static string Fail {
            get {
                return ResourceManager.GetString("Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Amis.
        /// </summary>
        public static string Friends {
            get {
                return ResourceManager.GetString("Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Groupe.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce groupe n&apos;existe pas.
        /// </summary>
        public static string GroupNotFound {
            get {
                return ResourceManager.GetString("GroupNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Groupes.
        /// </summary>
        public static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impossible.
        /// </summary>
        public static string ImpossibleAnswer {
            get {
                return ResourceManager.GetString("ImpossibleAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Langue.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paris en cours.
        /// </summary>
        public static string LblActiveBet {
            get {
                return ResourceManager.GetString("LblActiveBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à pari(s) en cours.
        /// </summary>
        public static string LblActiveBets {
            get {
                return ResourceManager.GetString("LblActiveBets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter des amis.
        /// </summary>
        public static string LblAddFriends {
            get {
                return ResourceManager.GetString("LblAddFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pari de.
        /// </summary>
        public static string LblBetOf {
            get {
                return ResourceManager.GetString("LblBetOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description.
        /// </summary>
        public static string LblBetPageDescription {
            get {
                return ResourceManager.GetString("LblBetPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Parier.
        /// </summary>
        public static string LblBtnBet {
            get {
                return ResourceManager.GetString("LblBtnBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Parié.
        /// </summary>
        public static string LblBtnBetSent {
            get {
                return ResourceManager.GetString("LblBtnBetSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Terminer.
        /// </summary>
        public static string LblBtnCloseNewBet {
            get {
                return ResourceManager.GetString("LblBtnCloseNewBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date pour répondre.
        /// </summary>
        public static string LblEndAnswerDate {
            get {
                return ResourceManager.GetString("LblEndAnswerDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fin du pari.
        /// </summary>
        public static string LblEndBetDate {
            get {
                return ResourceManager.GetString("LblEndBetDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paris existants.
        /// </summary>
        public static string LblExistingBets {
            get {
                return ResourceManager.GetString("LblExistingBets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dernier pari.
        /// </summary>
        public static string LblLastBet {
            get {
                return ResourceManager.GetString("LblLastBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mes amis.
        /// </summary>
        public static string LblMyFriends {
            get {
                return ResourceManager.GetString("LblMyFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paris terminés.
        /// </summary>
        public static string LblOverBet {
            get {
                return ResourceManager.GetString("LblOverBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Trouver des amis.
        /// </summary>
        public static string LblTitleSearchPage {
            get {
                return ResourceManager.GetString("LblTitleSearchPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Jeton(s).
        /// </summary>
        public static string LblTokens {
            get {
                return ResourceManager.GetString("LblTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier mon email.
        /// </summary>
        public static string LblUpdateEmail {
            get {
                return ResourceManager.GetString("LblUpdateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier mon mot de passe.
        /// </summary>
        public static string LblUpdatePassword {
            get {
                return ResourceManager.GetString("LblUpdatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier mon numéro de téléphone.
        /// </summary>
        public static string LblUpdatePhone {
            get {
                return ResourceManager.GetString("LblUpdatePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Utilisateurs qui m&apos;ont ajoutés.
        /// </summary>
        public static string LblUsersAddedMe {
            get {
                return ResourceManager.GetString("LblUsersAddedMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom d&apos;utilisateur.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connexion.
        /// </summary>
        public static string LogOn {
            get {
                return ResourceManager.GetString("LogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Déconnexion.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mes groupes de pari.
        /// </summary>
        public static string MainGroupTitle {
            get {
                return ResourceManager.GetString("MainGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Membres.
        /// </summary>
        public static string Membres {
            get {
                return ResourceManager.GetString("Membres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouveau.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouveau pari.
        /// </summary>
        public static string NewBet {
            get {
                return ResourceManager.GetString("NewBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouveau groupe.
        /// </summary>
        public static string NewGroup {
            get {
                return ResourceManager.GetString("NewGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouveau mot de passe.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Je ne participe pas.
        /// </summary>
        public static string NoAnswer {
            get {
                return ResourceManager.GetString("NoAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pas de résultat.
        /// </summary>
        public static string NoResult {
            get {
                return ResourceManager.GetString("NoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Participants.
        /// </summary>
        public static string Participants {
            get {
                return ResourceManager.GetString("Participants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mot de passe.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Téléphone.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OS inconnu.
        /// </summary>
        public static string PlatformUnknown {
            get {
                return ResourceManager.GetString("PlatformUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Possible.
        /// </summary>
        public static string PossibleAnswer {
            get {
                return ResourceManager.GetString("PossibleAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Profil.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inscription.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Perdu.
        /// </summary>
        public static string ResultLost {
            get {
                return ResourceManager.GetString("ResultLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gagné.
        /// </summary>
        public static string ResultWon {
            get {
                return ResourceManager.GetString("ResultWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recherche.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paramètres.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Statut : Terminé.
        /// </summary>
        public static string StatusEnd {
            get {
                return ResourceManager.GetString("StatusEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Statut : En cours.
        /// </summary>
        public static string StatusPending {
            get {
                return ResourceManager.GetString("StatusPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Succès.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Réponse : .
        /// </summary>
        public static string TextAnswerBet {
            get {
                return ResourceManager.GetString("TextAnswerBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Je parie que : (description).
        /// </summary>
        public static string TextBetDescription {
            get {
                return ResourceManager.GetString("TextBetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à parie que : .
        /// </summary>
        public static string TextLoginBet {
            get {
                return ResourceManager.GetString("TextLoginBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} a accepté votre demande d&apos;ami.
        /// </summary>
        public static string TextNotifAcceptedFriend {
            get {
                return ResourceManager.GetString("TextNotifAcceptedFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} veut vous ajouter dans sa liste d&apos;amis.
        /// </summary>
        public static string TextNotifAddFriend {
            get {
                return ResourceManager.GetString("TextNotifAddFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le pari de {0} est bientôt fini.
        /// </summary>
        public static string TextNotifBetAlmostOver {
            get {
                return ResourceManager.GetString("TextNotifBetAlmostOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} a répondu à un pari.
        /// </summary>
        public static string TextNotifBetAnswer {
            get {
                return ResourceManager.GetString("TextNotifBetAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} a terminé un pari.
        /// </summary>
        public static string TextNotifBetFinish {
            get {
                return ResourceManager.GetString("TextNotifBetFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} vous a lancé un nouveau pari.
        /// </summary>
        public static string TextNotifNewBet {
            get {
                return ResourceManager.GetString("TextNotifNewBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Il vous reste peu de temps pour répondre à ce pari.
        /// </summary>
        public static string TextNotifTimeToAnswer {
            get {
                return ResourceManager.GetString("TextNotifTimeToAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Il est temps de mettre fin à votre pari.
        /// </summary>
        public static string TextNotifTimeToFinish {
            get {
                return ResourceManager.GetString("TextNotifTimeToFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Résultat : .
        /// </summary>
        public static string TextResultBet {
            get {
                return ResourceManager.GetString("TextResultBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Temps restant pour parier : .
        /// </summary>
        public static string TimeToBet {
            get {
                return ResourceManager.GetString("TimeToBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Parier avec.
        /// </summary>
        public static string TitleBetUsersPage {
            get {
                return ResourceManager.GetString("TitleBetUsersPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cet utilisateur existe déjà.
        /// </summary>
        public static string UserExisting {
            get {
                return ResourceManager.GetString("UserExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Valider.
        /// </summary>
        public static string Validate {
            get {
                return ResourceManager.GetString("Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à J&apos;accepte.
        /// </summary>
        public static string YesAnswer {
            get {
                return ResourceManager.GetString("YesAnswer", resourceCulture);
            }
        }
    }
}
