//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetFriend.MobileApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BetFriend.MobileApp.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demande d&apos;ami.
        /// </summary>
        public static string AddedMe {
            get {
                return ResourceManager.GetString("AddedMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous n&apos;avez pas encore de compte ?.
        /// </summary>
        public static string AskAccount {
            get {
                return ResourceManager.GetString("AskAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demande d&apos;ajout envoyée.
        /// </summary>
        public static string AskFriendSent {
            get {
                return ResourceManager.GetString("AskFriendSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous avez déjà un compte ?.
        /// </summary>
        public static string AskSignIn {
            get {
                return ResourceManager.GetString("AskSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réponse trop tardive pour ce pari.
        /// </summary>
        public static string BadAnswerDate {
            get {
                return ResourceManager.GetString("BadAnswerDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cette date de fin de pari n&apos;est pas possible.
        /// </summary>
        public static string BadBetDate {
            get {
                return ResourceManager.GetString("BadBetDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informations incorrectes.
        /// </summary>
        public static string BadConnectionInfo {
            get {
                return ResourceManager.GetString("BadConnectionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mauvais format.
        /// </summary>
        public static string BadFormat {
            get {
                return ResourceManager.GetString("BadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non autorisé.
        /// </summary>
        public static string BadInformations {
            get {
                return ResourceManager.GetString("BadInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pari introuvable.
        /// </summary>
        public static string BetNotFound {
            get {
                return ResourceManager.GetString("BetNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ce pari est déjà terminé.
        /// </summary>
        public static string BetOver {
            get {
                return ResourceManager.GetString("BetOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S&apos;inscrire.
        /// </summary>
        public static string BtnTextRegister {
            get {
                return ResourceManager.GetString("BtnTextRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier mon mot de passe.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choisissez des amis pour ce pari.
        /// </summary>
        public static string ChooseFriends {
            get {
                return ResourceManager.GetString("ChooseFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmer le nouveau mot de passe.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmer le mot de passe.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe actuel.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de fin du pari.
        /// </summary>
        public static string DateEndToBet {
            get {
                return ResourceManager.GetString("DateEndToBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date pour parier.
        /// </summary>
        public static string DateToBet {
            get {
                return ResourceManager.GetString("DateToBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un champ est vide.
        /// </summary>
        public static string EmptyField {
            get {
                return ResourceManager.GetString("EmptyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de fin : .
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur est survenue.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informations d&apos;identification inconnues.
        /// </summary>
        public static string ErrorBadConnection {
            get {
                return ResourceManager.GetString("ErrorBadConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La date pour répondre au pari ne peut pas être après la date de fin du pari.
        /// </summary>
        public static string ErrorDateAnswerBet {
            get {
                return ResourceManager.GetString("ErrorDateAnswerBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La date pour répondre au pari ne peut pas être inférieure à la date du jour.
        /// </summary>
        public static string ErrorDateAnswerBetDateNow {
            get {
                return ResourceManager.GetString("ErrorDateAnswerBetDateNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les mots de passe ne sont pas identiques.
        /// </summary>
        public static string ErrorDifferentPassword {
            get {
                return ResourceManager.GetString("ErrorDifferentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La date de fin du pari ne peut pas être inférieure à la date du jour.
        /// </summary>
        public static string ErrorEndDateBet {
            get {
                return ResourceManager.GetString("ErrorEndDateBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cette adresse mail n&apos;est pas valide.
        /// </summary>
        public static string ErrorInvalidEmail {
            get {
                return ResourceManager.GetString("ErrorInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ce numéro de téléphone n&apos;est pas valide.
        /// </summary>
        public static string ErrorInvalidPhoneNumber {
            get {
                return ResourceManager.GetString("ErrorInvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le mot de passe doit contenir 6 caractères minimum.
        /// </summary>
        public static string ErrorLengthPassword {
            get {
                return ResourceManager.GetString("ErrorLengthPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tous les paramètres ne sont pas renseignés.
        /// </summary>
        public static string ErrorMissingParameters {
            get {
                return ResourceManager.GetString("ErrorMissingParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Échec.
        /// </summary>
        public static string Fail {
            get {
                return ResourceManager.GetString("Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amis.
        /// </summary>
        public static string Friends {
            get {
                return ResourceManager.GetString("Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groupe.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ce groupe n&apos;existe pas.
        /// </summary>
        public static string GroupNotFound {
            get {
                return ResourceManager.GetString("GroupNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groupes.
        /// </summary>
        public static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible.
        /// </summary>
        public static string ImpossibleAnswer {
            get {
                return ResourceManager.GetString("ImpossibleAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langue.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paris en cours.
        /// </summary>
        public static string LblActiveBet {
            get {
                return ResourceManager.GetString("LblActiveBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pari(s) en cours.
        /// </summary>
        public static string LblActiveBets {
            get {
                return ResourceManager.GetString("LblActiveBets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter des amis.
        /// </summary>
        public static string LblAddFriends {
            get {
                return ResourceManager.GetString("LblAddFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pari de.
        /// </summary>
        public static string LblBetOf {
            get {
                return ResourceManager.GetString("LblBetOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string LblBetPageDescription {
            get {
                return ResourceManager.GetString("LblBetPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parier.
        /// </summary>
        public static string LblBtnBet {
            get {
                return ResourceManager.GetString("LblBtnBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parié.
        /// </summary>
        public static string LblBtnBetSent {
            get {
                return ResourceManager.GetString("LblBtnBetSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminer.
        /// </summary>
        public static string LblBtnCloseNewBet {
            get {
                return ResourceManager.GetString("LblBtnCloseNewBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date pour répondre.
        /// </summary>
        public static string LblEndAnswerDate {
            get {
                return ResourceManager.GetString("LblEndAnswerDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fin du pari.
        /// </summary>
        public static string LblEndBetDate {
            get {
                return ResourceManager.GetString("LblEndBetDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paris existants.
        /// </summary>
        public static string LblExistingBets {
            get {
                return ResourceManager.GetString("LblExistingBets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dernier pari.
        /// </summary>
        public static string LblLastBet {
            get {
                return ResourceManager.GetString("LblLastBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mes amis.
        /// </summary>
        public static string LblMyFriends {
            get {
                return ResourceManager.GetString("LblMyFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paris terminés.
        /// </summary>
        public static string LblOverBet {
            get {
                return ResourceManager.GetString("LblOverBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trouver des amis.
        /// </summary>
        public static string LblTitleSearchPage {
            get {
                return ResourceManager.GetString("LblTitleSearchPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeton(s).
        /// </summary>
        public static string LblTokens {
            get {
                return ResourceManager.GetString("LblTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier mon email.
        /// </summary>
        public static string LblUpdateEmail {
            get {
                return ResourceManager.GetString("LblUpdateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier mon mot de passe.
        /// </summary>
        public static string LblUpdatePassword {
            get {
                return ResourceManager.GetString("LblUpdatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier mon numéro de téléphone.
        /// </summary>
        public static string LblUpdatePhone {
            get {
                return ResourceManager.GetString("LblUpdatePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilisateurs qui m&apos;ont ajoutés.
        /// </summary>
        public static string LblUsersAddedMe {
            get {
                return ResourceManager.GetString("LblUsersAddedMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom d&apos;utilisateur.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connexion.
        /// </summary>
        public static string LogOn {
            get {
                return ResourceManager.GetString("LogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Déconnexion.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mes groupes de pari.
        /// </summary>
        public static string MainGroupTitle {
            get {
                return ResourceManager.GetString("MainGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membres.
        /// </summary>
        public static string Membres {
            get {
                return ResourceManager.GetString("Membres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouveau.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouveau pari.
        /// </summary>
        public static string NewBet {
            get {
                return ResourceManager.GetString("NewBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouveau groupe.
        /// </summary>
        public static string NewGroup {
            get {
                return ResourceManager.GetString("NewGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouveau mot de passe.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je ne participe pas.
        /// </summary>
        public static string NoAnswer {
            get {
                return ResourceManager.GetString("NoAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pas de résultat.
        /// </summary>
        public static string NoResult {
            get {
                return ResourceManager.GetString("NoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant(s).
        /// </summary>
        public static string Participants {
            get {
                return ResourceManager.GetString("Participants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Téléphone.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS inconnu.
        /// </summary>
        public static string PlatformUnknown {
            get {
                return ResourceManager.GetString("PlatformUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possible.
        /// </summary>
        public static string PossibleAnswer {
            get {
                return ResourceManager.GetString("PossibleAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inscription.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perdu.
        /// </summary>
        public static string ResultLost {
            get {
                return ResourceManager.GetString("ResultLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gagné.
        /// </summary>
        public static string ResultWon {
            get {
                return ResourceManager.GetString("ResultWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recherche.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramètres.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statut : Terminé.
        /// </summary>
        public static string StatusEnd {
            get {
                return ResourceManager.GetString("StatusEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statut : En cours.
        /// </summary>
        public static string StatusPending {
            get {
                return ResourceManager.GetString("StatusPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S&apos;abonner.
        /// </summary>
        public static string Subscribe {
            get {
                return ResourceManager.GetString("Subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succès.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réponse : .
        /// </summary>
        public static string TextAnswerBet {
            get {
                return ResourceManager.GetString("TextAnswerBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je parie que : (description).
        /// </summary>
        public static string TextBetDescription {
            get {
                return ResourceManager.GetString("TextBetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parie que : .
        /// </summary>
        public static string TextLoginBet {
            get {
                return ResourceManager.GetString("TextLoginBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} a accepté votre demande d&apos;ami.
        /// </summary>
        public static string TextNotifAcceptedFriend {
            get {
                return ResourceManager.GetString("TextNotifAcceptedFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} veut vous ajouter dans sa liste d&apos;amis.
        /// </summary>
        public static string TextNotifAddFriend {
            get {
                return ResourceManager.GetString("TextNotifAddFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le pari de {0} est bientôt fini.
        /// </summary>
        public static string TextNotifBetAlmostOver {
            get {
                return ResourceManager.GetString("TextNotifBetAlmostOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} a répondu à un pari.
        /// </summary>
        public static string TextNotifBetAnswer {
            get {
                return ResourceManager.GetString("TextNotifBetAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} a terminé un pari.
        /// </summary>
        public static string TextNotifBetFinish {
            get {
                return ResourceManager.GetString("TextNotifBetFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} vous a lancé un nouveau pari.
        /// </summary>
        public static string TextNotifNewBet {
            get {
                return ResourceManager.GetString("TextNotifNewBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il vous reste peu de temps pour répondre à ce pari.
        /// </summary>
        public static string TextNotifTimeToAnswer {
            get {
                return ResourceManager.GetString("TextNotifTimeToAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il est temps de mettre fin à votre pari.
        /// </summary>
        public static string TextNotifTimeToFinish {
            get {
                return ResourceManager.GetString("TextNotifTimeToFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Résultat : .
        /// </summary>
        public static string TextResultBet {
            get {
                return ResourceManager.GetString("TextResultBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temps restant pour parier : .
        /// </summary>
        public static string TimeToBet {
            get {
                return ResourceManager.GetString("TimeToBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parier avec.
        /// </summary>
        public static string TitleBetUsersPage {
            get {
                return ResourceManager.GetString("TitleBetUsersPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se désabonner.
        /// </summary>
        public static string UnSubscribe {
            get {
                return ResourceManager.GetString("UnSubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cet utilisateur existe déjà.
        /// </summary>
        public static string UserExisting {
            get {
                return ResourceManager.GetString("UserExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valider.
        /// </summary>
        public static string Validate {
            get {
                return ResourceManager.GetString("Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to J&apos;accepte.
        /// </summary>
        public static string YesAnswer {
            get {
                return ResourceManager.GetString("YesAnswer", resourceCulture);
            }
        }
    }
}
